sudo: false
language: ruby
cache: bundler
script: bundle exec rake release_checks
before_install:
- gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.3
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.3
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.3.3
    bundler_args: "--without system_tests"
    env: PUPPET_GEM_VERSION="~> 5.0"
notifications:
  email: false
  slack:
    rooms:
      secure: "TMCILa8iQjUUytjfJNS2gUzX7I3Rj23WR7fSnL0ZE4yERqsIrl0SsOAvfjAPNHKC3nbn+Zdwq4mnfAbC8hK+OAzIgJAk4jj0JZ+VUh6M+IM2TzwKdDz+gLZbfhFYLZ3ObECqPbTW7n9vpELIpuMiwwHYB6DVIxJBAxmNZn0vt/ba6FhhZmIWbwT+PR0k69UOcD94KBs4wkLSQLngxgJrBE+JhK8iOIx9zKmsZKVYcpdqe5tkgCdgCToBt5jBZWNbPiPADk4Jh0PiBb90j5BbKPMM8ALe/cvM7DIk/vQHij6eqx1nd+0VYN0epxDgdtyEPosK2kDAx4+sR+4Wo9wthMGfdaN1QEVGU4o61fZBYDmJ1u9fg77Vr0L45lpMqO/XZzFaIb96Q7YTni3w9MMgiDhPXrHugVqKaU9NvzVkXJkLRg8LcKFQXciGv24rBuY2LOLzl5dBAtgBlccO3DoUa7M7s6QNnwCa1ZOJLSqhQuNHqjopI0fACEsptCzHIlknr7cBmMpgH2oSPeQ9q0XuMvziddLp2xy526lyVY+Q4TMWlB5qn6gxw76XQyx6bbZmRzfwffiKu6zfFQfneIsP3ZgzuK/KRCKC3h2Fdy8VmnncrRqWODOZ1mka1v/ZRMknHpo34+cboEOC3MiWvAYosog5qp8ZK8mNWytmK+WpbEY="
